FROM hdf5-develop

RUN apt-get update

# Install python and its utilities
RUN apt-get install -y python3-dev python-numpy python3-numpy python3-pip

# Installing build automation systems
RUN apt-get install -y cmake make

RUN apt-get install -y vim git # Always useful

RUN apt-get install -y libz-dev # Needed for h5part

COPY . /PyVOL

WORKDIR /PyVOL/src/python

RUN python3 setup.py install

WORKDIR /PyVOL
