FROM hdf5-develop

RUN apt-get update

# Install python and its utilities
RUN apt-get install -y python3-dev python-numpy python3-numpy python3-pip

# Installing build automation systems
RUN apt-get install -y cmake make

RUN apt-get install -y vim git # Always useful

RUN apt-get install -y libz-dev # Needed for h5part

### Configuring ssh connection
RUN apt-get install -y openssh-server
RUN ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa
RUN cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
## Insecure - just for testing
RUN echo 'Host *' >> /root/.ssh/config
RUN echo '    StrictHostKeyChecking no' >> /root/.ssh/config
RUN chmod 400 /root/.ssh/config

COPY . /H5PyVOL

WORKDIR /H5PyVOL/src/python

RUN python3 setup.py install

WORKDIR /H5PyVOL
